#!/bin/bash

# Execute the following as root to install lintian
# apt-get install lintian

# Then run this file, altering the version.
# After building the package, this script will run it against lintian
# to highlight potential issues to the builder.

set -eu

VERSION=2.2.0-1
SOURCE_DIR=~/debbuild/source
BUILD_DIR=~/debbuild/build
TAR_FILE=${VERSION}.tar.gz

# Create SSM and DEB dir (if not present)
mkdir -p $SOURCE_DIR
mkdir -p $BUILD_DIR

# Clean up any previous build
rm -rf $SOURCE_DIR/*
rm -rf $BUILD_DIR/*

# Get and extract the source
TAR_URL=https://github.com/apel/ssm/archive/$TAR_FILE
wget --no-check-certificate $TAR_URL -O $TAR_FILE
tar xvf $TAR_FILE -C $SOURCE_DIR
rm -f $TAR_FILE

fpm -s python -t deb \
-n apel-ssm \
-v $VERSION \
-m "Apel Administrators <apel-admins@stfc.ac.uk>" \
--description "Secure Stomp Messenger (SSM)." \
--deb-changelog CHANGELOG \
--python-install-bin /usr/bin \
--python-install-lib /usr/lib/python2.7/dist-packages \
$SOURCE_DIR/ssm-$VERSION/setup.py

mv ./apel-ssm_${VERSION}_all.deb $BUILD_DIR

# Check the resultant deb for 'lint'
echo "Possible Issues to Fix:"
lintian $BUILD_DIR/apel-ssm_${VERSION}_all.deb
